#!/usr/bin/env python3
"""Puts the recomp build's HLE globals at their DOL addresses.

The recomp build runs the game's own machine code, which reaches its globals at their DOL
addresses. The HLE module (the runtime's SDK replacement, linked alone by gcn_hle_build.py)
must use the same storage for every global both sides know by name: the SDK state the game
touches directly, and the game data the SDK replacement refers to (stand-ins generated by
gcn_hle_build.py). This moves each such data symbol to its address in the decomp's
symbols.txt (unique global names only), retargets the relocations that reach it, and fills
gcn_hle_place_table (Runtime/recomp/hle_raw/hle_entry.c) so the initial contents are copied
over the DOL's data at boot.

    gcn_hle_place.py <hle.wasm> <hle.map> <symbols.txt> [<recompiler syms.txt>]

The recompiler's syms.txt adds the decomp's own names of the game's globals (its `data` lines,
gcn_syms.py --placed), which the game package's mods use; symbols.txt names many of them lbl_*.

Reuses gcn_place.py's wasm reader. Writes <hle>.syms (address 0 size name) like gcn_place.py.
"""
import bisect
import os
import struct
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
import gcn_place as gp  # noqa: E402

PLACEABLE = ('runtime_', 'gen_hle_data')  # object stems whose globals may move


def main():
    if len(sys.argv) not in (4, 5):
        print(__doc__)
        return 2
    wasm_path, map_path, symbols_path = sys.argv[1:4]
    w = gp.Wasm(open(wasm_path, 'rb').read())
    by_name, _ = gp.read_symbols(symbols_path)
    # the decomp's names (statics too): only for stand-ins, never to move the runtime's own globals
    decomp_names = {}
    if len(sys.argv) == 5:
        for line in open(sys.argv[4], encoding='utf-8'):
            f = line.split()
            if len(f) == 4 and f[0] == 'data':
                decomp_names[f[3]] = [(int(f[1], 16), int(f[2], 16), False, '.data')]
    objects = gp.read_map_objects(map_path)

    placed, taken, skipped = {}, [], []
    standins = set()  # the game's own variables (gen/hle_data_stubs.c): never copied over the DOL's data

    def free(a, n):
        j = bisect.bisect_left(taken, (a, a + n))
        if j > 0 and taken[j - 1][1] > a:
            return False
        return not (j < len(taken) and taken[j][0] < a + n)

    for idx, (k, flags, name, addr, size) in enumerate(w.symbols):
        if k != gp.SYM_DATA or addr is None or flags & gp.SYM_UNDEFINED or not size or not name:
            continue
        obj = objects.get((name, addr))
        if not obj or not obj.startswith(PLACEABLE):
            continue
        cands = [c for c in by_name.get(name, []) if not c[2]]  # global symbols of that name
        if not cands and obj.startswith('gen_hle_data'):
            cands = decomp_names.get(name, [])
        if len(cands) != 1:
            continue
        a, osize = cands[0][0], cands[0][1]
        if osize and size > osize:
            skipped.append('%s (%d bytes here, %d in the DOL)' % (name, size, osize))
            continue
        if not free(a, size):
            skipped.append('%s (overlaps another placed global)' % name)
            continue
        bisect.insort(taken, (a, a + size))
        placed[idx] = a
        if obj.startswith('gen_hle_data'):
            standins.add(idx)

    fixed = 0
    for target, t, off, idx, addend in w.relocs:
        if idx not in placed or t not in (gp.R_MEMORY_ADDR_LEB, gp.R_MEMORY_ADDR_SLEB, gp.R_MEMORY_ADDR_I32):
            continue
        k, flags, name, addr, size = w.symbols[idx]
        old = (addr + addend) & 0xFFFFFFFF
        new = (placed[idx] + addend) & 0xFFFFFFFF
        if t == gp.R_MEMORY_ADDR_I32:
            assert struct.unpack_from('<I', w.b, off)[0] == old, name
            struct.pack_into('<I', w.b, off, new)
        else:
            assert gp.padded(w.b, off), name
            cur, _ = (gp.uleb if t == gp.R_MEMORY_ADDR_LEB else gp.sleb)(w.b, off)
            assert cur & 0xFFFFFFFF == old, name
            (gp.put_uleb5 if t == gp.R_MEMORY_ADDR_LEB else gp.put_sleb5)(w.b, off, new)
        fixed += 1

    table = [s for s in w.symbols if s[0] == gp.SYM_DATA and s[2] == 'gcn_hle_place_table' and s[3] is not None]
    assert table, 'gcn_hle_place_table missing (Runtime/recomp/hle_raw/hle_entry.c)'
    taddr, tsize = table[0][3], table[0][4]
    toff = w.data_offset(taddr)
    assert struct.unpack_from('<I', w.b, toff)[0] == gp.PLACE_MAGIC
    entries = []
    for idx, a in sorted(placed.items(), key=lambda x: x[1]):
        _, _, name, addr, size = w.symbols[idx]
        if idx in standins or w.data_bytes(addr, size) is None:
            continue  # the game's own data, or bss (the DOL's bss is zeroed at boot)
        entries.append([a, addr, size])
    cap = (tsize // 4 - 4) // 3
    assert len(entries) <= cap, 'gcn_hle_place_table holds %d entries, %d needed' % (cap, len(entries))
    struct.pack_into('<4I', w.b, toff, gp.PLACE_MAGIC, len(entries), 0, 0)
    for i, (a, addr, size) in enumerate(entries):
        struct.pack_into('<3I', w.b, toff + 4 * (4 + 3 * i), a, addr, size)

    with open(os.path.splitext(wasm_path)[0] + '.syms', 'w', encoding='utf-8') as f:
        f.write('# HLE data symbols after gcn_hle_place.py: address 0 size name\n')
        for i, (k, flags, name, addr, size) in enumerate(w.symbols):
            if k == gp.SYM_DATA and addr is not None and name and not name.startswith('.L'):
                f.write('%08x 0 %x %s\n' % (placed.get(i, addr), size, name))

    out = bytearray(w.b[:8])
    for sid, name, start, end in w.sections:
        if sid == 0 and (name == 'linking' or name.startswith('reloc.')):
            continue
        hdr = bytearray([sid])
        n = end - start
        while True:
            x = n & 0x7F
            n >>= 7
            hdr.append(x | (0x80 if n else 0))
            if not n:
                break
        out += hdr + w.b[start:end]
    tmp = wasm_path + '.tmp'
    open(tmp, 'wb').write(out)
    os.replace(tmp, wasm_path)
    print('gcn_hle_place: %d HLE globals at their DOL addresses, %d references moved, %d copies at boot'
          % (len(placed), fixed, len(entries)))
    for s in skipped:
        print('gcn_hle_place: not placed: ' + s)
    return 0


if __name__ == '__main__':
    sys.exit(main())
