#!/usr/bin/env python3
"""Builds the recomp build's HLE module: com.recomp.gcn's SDK replacement (Runtime/guest),
compiled through the decomp build's own pipeline (gcn_build.py) but without the game.

    gcn_hle_build.py <game Native dir> --syms <recompiler syms.txt> --out <dir>
                     [--name sfa_recomp] [--config Release] [--register --runtime-include=...]

The recompiled game (GcnRecomp) calls the functions the decomp build takes from the runtime
(`hle` lines of syms.txt); this module supplies them, as a wasm2c module named <name> whose
descriptor (<name>_guest_module.c) GcnGuestHost and the runner run like any GameCube game:
its gcn_game_entry (Runtime/recomp/hle_raw/hle_entry.c) loads the DOL and boots, and the
`main` it calls is the recompiled one.

  - The game's data the runtime refers to by name gets stand-ins (gen/hle_data_stubs.c),
    placed with the runtime's own shared globals at their DOL addresses (gcn_hle_place.py).
  - The game's functions the runtime calls (main, callbacks by name) become imports; the
    recomp runtime implements them by calling the recompiled code (gen_hle_glue.py).

Intermediates go to <Native>/build/recomp-hle-<config>, the C to --out. Nothing the decomp
build writes is touched.
"""
import argparse
import hashlib
import json
import os
import re
import sys
from concurrent.futures import ThreadPoolExecutor

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLS = os.path.dirname(HERE)
RUNTIME = os.path.dirname(TOOLS)
sys.path.insert(0, TOOLS)
import gcn_build  # noqa: E402
import gcn_ir  # noqa: E402

HLE_BASE = 0x81800000  # just above the game's 24 MB (still inside the runtime's 32 MB buffer)
HLE_END = 0x82000000
SYM_RE = re.compile(r'^(\S+) = (\.?\w+):0x([0-9A-Fa-f]+); // type:(\w+)(?: size:0x([0-9A-Fa-f]+))?(.*)$')


def dtk_symbols(path):
    out = {}
    for line in open(path, encoding='utf-8'):
        m = SYM_RE.match(line.strip())
        if m:
            name, _, addr, kind, size, rest = m.groups()
            if 'scope:local' in rest:
                continue
            out.setdefault(name, (kind, int(addr, 16), int(size or '0', 16)))
    return out


class HleBuild(gcn_build.Build):
    def __init__(self, native, config, jobs, name):
        super().__init__(native, config, jobs, False)
        self.out = os.path.join(self.native, 'build', 'recomp-hle-' + config)
        self.name = name

    def units(self):
        units = []
        for f in sorted(gcn_build.glob.glob(os.path.join(RUNTIME, 'guest', '**', '*.c'), recursive=True)):
            rel = os.path.relpath(f, os.path.join(RUNTIME, 'guest')).replace('\\', '/')
            if rel.split('/')[0] in self.cfg.get('runtime_exclude', []):
                continue
            units.append(gcn_build.Unit('runtime/' + rel, f, f, 'runtime'))
        return units

    def write_mods_list(self, units):
        # mods are decomp-build only for now
        gcn_build.write_if_changed(os.path.join(self.out, 'gen', 'gcn_mods_list.c'),
                                   '/* recomp build: no mods */\nvoid gcn_mods_init_all(void)\n{\n}\n')

    def stubs_unit(self):
        f = os.path.join(self.out, 'gen', 'hle_data_stubs.c')
        if not os.path.exists(f):
            gcn_build.write_if_changed(f, '/* generated by gcn_hle_build.py */\n')
        return gcn_build.Unit('gen/hle_data_stubs.c', f, f, 'runtime')

    def raw_objects(self):
        objs = []
        for f in [os.path.join(RUNTIME, 'guest_raw', 'libm.c'), os.path.join(RUNTIME, 'recomp', 'hle_raw', 'hle_entry.c')]:
            obj = os.path.join(self.out, 'obj', 'raw_' + os.path.splitext(os.path.basename(f))[0] + '.o')
            if gcn_build.mtime(obj) < gcn_build.mtime(f):
                os.makedirs(os.path.dirname(obj), exist_ok=True)
                rc, out = gcn_build.run([self.tc.wclang, '--target=wasm32', '-O2', '-mnontrapping-fptoint', '-mbulk-memory',
                                         '-ffreestanding', '-nostdlib', '-c', f, '-o', obj])
                if rc:
                    raise SystemExit('gcn_hle_build: %s\n%s' % (f, out))
            objs.append(obj)
        return objs

    def compile_all(self, units):
        pdir = self.apply_patches(units)
        flags = self.front_flags(pdir)
        flags_hash = hashlib.sha1(json.dumps(flags).encode()).hexdigest()
        with ThreadPoolExecutor(self.jobs) as pool:
            res = list(pool.map(lambda u: self.compile_unit(u, flags, flags_hash, None), units))
        units = self.report(res, 'compile')
        weak_file = os.path.join(self.out, 'weak.txt')
        sig_file = os.path.join(self.out, 'signatures.txt')
        cnt = gcn_build.collections.Counter()
        sigs = {}
        for u in units:
            text = open(os.path.join(self.out, 'ir', u.stem + '.ll'), encoding='utf-8').read()
            cnt.update(set(gcn_ir.defined_functions(text)))
            for name, sig in gcn_ir.function_signatures(text).items():
                sigs[name] = sig if sigs.get(name, sig) == sig else None
        gcn_build.write_if_changed(weak_file, '\n'.join(sorted(n for n, c in cnt.items() if c > 1)) + '\n')
        gcn_build.write_if_changed(sig_file, gcn_ir.write_signatures(sig_file, sigs))
        with ThreadPoolExecutor(self.jobs) as pool:
            res = list(pool.map(lambda u: self.lower_unit(u, weak_file, sig_file), units))
        return self.report(res, 'lower')

    def link_hle(self, units, exports, game_functions):
        objs = [os.path.join(self.out, 'obj', u.stem + '.o') for u in units] + self.raw_objects()
        wasm = os.path.join(self.out, self.name + '.wasm')
        imports = os.path.join(self.out, 'imports.txt')
        host = [l.strip() for l in open(os.path.join(TOOLS, 'gcn_imports.txt')) if l.strip() and not l.startswith('#')]
        gcn_build.write_if_changed(imports, '\n'.join(host + sorted(game_functions)) + '\n')
        rsp = os.path.join(self.out, 'link.rsp')
        gcn_build.write_if_changed(rsp, '\n'.join('"%s"' % o.replace('\\', '/') for o in objs))
        cmd = [self.tc.wasm_ld, '--no-entry', '--no-gc-sections', '--no-stack-first', '--emit-relocs',
               '--export=__stack_pointer', '--allow-undefined-file=' + imports, '--error-limit=0',
               '--global-base=%d' % HLE_BASE, '--initial-memory=%d' % HLE_END, '--max-memory=%d' % HLE_END,
               '-z', 'stack-size=%d' % 0x40000, '--Map=' + os.path.join(self.out, self.name + '.map'),
               '@' + rsp, '-o', wasm]
        cmd += ['--export-if-defined=' + n for n in sorted(exports)]
        rc, out = gcn_build.run(cmd)
        open(os.path.join(self.out, 'link.log'), 'w').write(out)
        undefined = sorted(set(re.findall(r'undefined symbol: (\S+)', out)))
        return rc, out, undefined, wasm


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('native')
    ap.add_argument('--syms', required=True, help='the recompiler symbol file (gcn_syms.py)')
    ap.add_argument('--out', required=True)
    ap.add_argument('--name', default=None, help='module name (default <game name>recomp)')
    ap.add_argument('--config', default='Release')
    ap.add_argument('--jobs', type=int, default=os.cpu_count() or 4)
    ap.add_argument('--register', action='store_true')
    ap.add_argument('--runtime-include', default='')
    a = ap.parse_args()

    b = HleBuild(a.native, a.config, a.jobs, None)
    b.name = a.name or (b.cfg['name'] + 'recomp')  # no underscore: gcn_wasm_to_c.py's module file pastes it into wasm2c names
    os.makedirs(b.out, exist_ok=True)
    symbols_txt = b.layout_file('symbols', 'config/{version}/symbols.txt')
    if not symbols_txt:
        raise SystemExit('gcn_hle_build: the decomp has no symbols.txt for %s' % b.version)
    dtk = dtk_symbols(symbols_txt)
    hle = [l.split()[1] for l in open(a.syms) if l.startswith('hle ')]

    b.extract()
    units = b.units()
    b.write_mods_list(units)
    units = b.units_with_generated(units) + [b.stubs_unit()]

    # link; game data the runtime names gets stand-ins, game functions become imports; again
    game_functions = set()
    for attempt in range(4):
        built = b.compile_all(units)
        rc, out, undefined, wasm = b.link_hle(built, hle, game_functions)
        if rc == 0:
            break
        unknown, data = [], []
        for n in undefined:
            kind = dtk.get(n, (None,))[0]
            if kind == 'function' and n not in game_functions:
                game_functions.add(n)
            elif kind == 'object':
                data.append(n)
            elif n not in game_functions:
                unknown.append(n)
        if unknown:
            raise SystemExit('gcn_hle_build: undefined, and not in the game either: ' + ' '.join(unknown))
        stub = os.path.join(b.out, 'gen', 'hle_data_stubs.c')
        old = open(stub, encoding='utf-8').read()
        lines = [l for l in old.splitlines() if l.startswith('unsigned char ')]
        have = {l.split()[2].split('[')[0] for l in lines}
        for n in data:
            if n not in have:
                lines.append('unsigned char %s[%d] __attribute__((aligned(4)));' % (n, max(dtk[n][2], 4)))
        gcn_build.write_if_changed(stub, '/* generated by gcn_hle_build.py: game data the runtime refers to, '
                                         'placed at their DOL addresses by gcn_hle_place.py */\n' + '\n'.join(sorted(lines)) + '\n')
    else:
        raise SystemExit('gcn_hle_build: link failed (%s)' % os.path.join(b.out, 'link.log'))
    with open(os.path.join(b.out, 'game_functions.txt'), 'w', newline='\n') as f:
        f.write(''.join('%s 0x%08X\n' % (n, dtk[n][1]) for n in sorted(game_functions)))
    print('gcn_hle_build: linked %s (%d game functions imported)' % (os.path.basename(wasm), len(game_functions)))

    rc, out = gcn_build.run([sys.executable, os.path.join(HERE, 'gcn_hle_place.py'), wasm,
                             os.path.join(b.out, b.name + '.map'), symbols_txt])
    print(out.strip())
    if rc:
        raise SystemExit('gcn_hle_build: placing failed')

    cmd = [sys.executable, os.path.join(TOOLS, 'gcn_wasm_to_c.py'), b.tc.wasm2c, wasm, a.out, b.name, '4',
           '--package=' + b.cfg.get('package', ''), '--title=' + b.cfg.get('title', b.name),
           '--disc=' + os.path.basename(b.cfg.get('disc', ''))]
    syms = os.path.splitext(wasm)[0] + '.syms'
    if os.path.isfile(syms):
        cmd.append('--syms=' + syms)
    if a.register:
        cmd += ['--register', '--runtime-include=' + a.runtime_include]
    elif a.runtime_include:
        cmd.append('--runtime-include=' + a.runtime_include)
    rc, out = gcn_build.run(cmd)
    print(out.strip())
    if rc:
        raise SystemExit('gcn_hle_build: wasm2c failed')
    # indirect calls: the instance argument must not index the table with a PowerPC address
    # (gcnw_ops.h GCNW_RECOMP)
    for f in os.listdir(a.out):
        if f.startswith(b.name + '_guest_') and f.endswith('.c'):
            path = os.path.join(a.out, f)
            text = open(path, encoding='utf-8').read()
            new = re.sub(r'(instance->w2c_T0)\.data\[(\w+)\]\.module_instance', r'GCNW_TABLE_INSTANCE(\1, \2)', text)
            if new != text:
                open(path, 'w', encoding='utf-8', newline='\n').write(new)
    import shutil
    shutil.copyfile(os.path.join(b.out, 'game_functions.txt'), os.path.join(a.out, b.name + '_game_functions.txt'))
    return 0


if __name__ == '__main__':
    sys.exit(main())
