#!/usr/bin/env python3
"""Builds a Live recomp build's symbols into its library.

    gcn_live_syms.py <recompiler syms.txt> <out.c>

A Live build recompiles the game from the player's disc when it starts (Runtime/recomp/live);
what it needs besides the disc is the recompiler's symbol file: function names and sizes, switch
tables, the small-data bases, the HLE list - names and addresses, no game code. This writes it as
`gcnr_live_syms` / `gcnr_live_syms_size` (recomp_live.cpp), without the `data` lines (those are
for the HLE module's build) and comments.
"""
import os
import sys


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    syms, out = sys.argv[1:]
    lines = [l.rstrip('\r\n') for l in open(syms, encoding='utf-8')]
    keep = '\n'.join(l for l in lines if l and not l.startswith('#') and not l.startswith('data ')) + '\n'
    data = keep.encode('utf-8')
    rows = []
    for i in range(0, len(data), 32):
        rows.append(','.join(str(b) for b in data[i:i + 32]))
    text = ('/* Generated by gcn_live_syms.py from %s - do not edit. The recompiler\'s symbols for a Live\n'
            ' * build (names and addresses only). */\n'
            'const unsigned char gcnr_live_syms[] = {\n%s\n};\n'
            'const unsigned int gcnr_live_syms_size = %d;\n') % (os.path.basename(syms), ',\n'.join(rows), len(data))
    old = open(out, encoding='utf-8').read() if os.path.exists(out) else None
    if old != text:
        with open(out, 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)
    print('gcn_live_syms: %d bytes of symbols' % len(data))
    return 0


if __name__ == '__main__':
    sys.exit(main())
