#!/usr/bin/env python3
"""Writes the glue between the recompiled game and the HLE module (gcn_hle_build.py).

    gen_hle_glue.py <hle dir> <module name> <recompiler syms.txt> <out.c>

 - hle_<name>(mem, c): one per function the recompiled code calls instead of the original
   (syms.txt `hle` lines). Takes the PowerPC EABI arguments from the registers (r3-r10, then
   the stack from 8(r1); f1-f8; 64-bit values in aligned register pairs), calls the wasm2c
   export with the HLE stack just below the caller's, and puts the result in r3 / r3:r4 / f1.
   OSReport and OSPanic build the big-endian variadic buffer the HLE takes (gcnr_va_build).
 - w2c_env_<name>: the game functions the HLE calls (<module>_game_functions.txt: main, the
   C library's sprintf/vsprintf, what the game package's mods call, ...), as calls of the
   recompiled code (gcnr_call_guest, or gcnr_call_ctx with floating point arguments).
 - gcnr_hle_functions[]: every hle_<name> by name (Live builds look them up by address).
"""
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
from gcn_wasm_to_c import mangle  # noqa: E402

VARIADIC = {'OSReport': 0, 'OSPanic': 2}  # index of the format argument
EXPORT_RE = re.compile(r"/\* export: '([^']+)' \*/\s*\n(\w+) (w2c_\w+)\(([^)]*)\);")
IMPORT_RE = re.compile(r"/\* import: 'env' '([^']+)' \*/\s*\n(\w+) (w2c_env_\w+)\(([^)]*)\);")


def params(text):
    parts = [p.strip() for p in text.split(',')]
    return [p for p in parts[1:] if p]  # drop the instance / env pointer


def main():
    if len(sys.argv) != 5:
        print(__doc__)
        return 2
    hle_dir, name, syms_path, out_path = sys.argv[1:]
    header = open(os.path.join(hle_dir, name + '_guest.h'), encoding='utf-8').read()
    exports = {m.group(1): (m.group(2), m.group(3), params(m.group(4))) for m in EXPORT_RE.finditer(header)}
    imports = {m.group(1): (m.group(2), m.group(3), params(m.group(4))) for m in IMPORT_RE.finditer(header)}
    hle = [l.split()[1] for l in open(syms_path) if l.startswith('hle ')]
    game = {}
    gf = os.path.join(hle_dir, name + '_game_functions.txt')
    if os.path.isfile(gf):
        for l in open(gf):
            if l.strip():
                n, a = l.split()
                game[n] = int(a, 16)
    inst = 'w2c_' + mangle(name)

    o = []
    o.append('/* Generated by gen_hle_glue.py - do not edit. Glue between the recompiled game and the %s HLE module. */' % name)
    o.append('#include <stddef.h>\n#include "gcn_recomp.h"\n#include "gcnw_module.h"\n#include "%s_guest.h"\n' % name)
    o.append('extern const GcnwModule gcnw_module_%s;' % name)
    o.append('uint32_t gcnr_va_build(uint8_t* mem, gcnr_ctx* c, int fixed, uint32_t at);')
    o.append('uint32_t gcnr_call_guest(uint32_t addr, int n, const uint32_t* args);')
    o.append('void gcnr_init_ctx(gcnr_ctx* c);')
    o.append('uint32_t gcnr_call_ctx(gcnr_ctx* c, uint32_t addr);')
    o.append('uint32_t gcnr_call_vsprintf(uint32_t addr, uint32_t buf, uint32_t fmt, uint32_t ap);')
    o.append('void gcnr_run_ctors(void);')
    o.append('extern int gcnr_trace_left;')
    o.append('void gcnr_trace_hle(const char* name, uint8_t* mem, gcnr_ctx* c);\n')
    o.append('const GcnwModule* gcnr_module(void)\n{\n    return &gcnw_module_%s;\n}\n' % name)
    o.append('static %s* hle(void)\n{' % inst)
    o.append('    static %s* sInst;' % inst)
    o.append('    if (!sInst) sInst = (%s*)((char*)gcnw_module_%s.memory() - offsetof(%s, w2c_memory));' % (inst, name, inst))
    o.append('    return sInst;\n}\n')
    o.append('/* the HLE stack just below the calling game code\'s (its frames must stay intact) */')
    o.append('#define HLE_ENTER(c) uint32_t* sp_ = gcnw_module_%s.stack_pointer(); const uint32_t saved_ = *sp_; '
             '*sp_ = ((c)->r[1] - 64u) & ~15u' % name)
    o.append('#define HLE_LEAVE() *sp_ = saved_\n')

    missing = []
    for n in hle:
        if n not in exports:
            missing.append(n)
            continue
        ret, fn, ps = exports[n]
        o.append('void hle_%s(uint8_t* mem, gcnr_ctx* c)\n{' % n)
        gpr, fpr, stack, args = 3, 1, 0, []
        fixed = VARIADIC.get(n)
        for i, p in enumerate(ps):
            if fixed is not None and i == fixed + 1:
                args.append('va')  # the variadic buffer
                continue
            if p == 'u64':
                if gpr % 2 == 0:
                    gpr += 1
                args.append('((uint64_t)c->r[%d] << 32 | c->r[%d])' % (gpr, gpr + 1))
                gpr += 2
            elif p in ('f32', 'f64'):
                args.append('(%s)c->f[%d].ps0' % ('float' if p == 'f32' else 'double', fpr))
                fpr += 1
            elif gpr <= 10:
                args.append('c->r[%d]' % gpr)
                gpr += 1
            else:
                args.append('gcnr_lw(mem, c->r[1] + %du)' % (8 + 4 * stack))
                stack += 1
        o.append('    if (GCNR_UNLIKELY(gcnr_trace_left)) gcnr_trace_hle("%s", mem, c);' % n)
        o.append('    HLE_ENTER(c);')
        if fixed is not None:
            o.append('    const uint32_t va = gcnr_va_build(mem, c, %d, *sp_);' % (fixed + 1))
            o.append('    *sp_ = (va - 16u) & ~15u;')
        call = '%s(hle()%s)' % (fn, ''.join(', ' + a for a in args))
        if ret == 'void':
            o.append('    %s;' % call)
        elif ret == 'u64':
            o.append('    const uint64_t r = %s;' % call)
            o.append('    c->r[3] = (uint32_t)(r >> 32);\n    c->r[4] = (uint32_t)r;')
        elif ret in ('f32', 'f64'):
            o.append('    const double r = %s;' % call)
            o.append('    c->f[1].ps0 = r;\n    c->f[1].ps1 = r;')
        else:
            o.append('    c->r[3] = %s;' % call)
        o.append('    HLE_LEAVE();\n}\n')

    for n, (ret, fn, ps) in sorted(imports.items()):
        if n not in game:
            continue  # a host import (gcnw_backend.c)
        sig = ', '.join('%s a%d' % ({'u32': 'uint32_t', 'u64': 'uint64_t', 'f32': 'float', 'f64': 'double'}[p], i)
                        for i, p in enumerate(ps))
        cret = {'void': 'void', 'u32': 'uint32_t', 'u64': 'uint64_t', 'f32': 'float', 'f64': 'double'}[ret]
        o.append('%s %s(struct w2c_env* env%s)\n{' % (cret, fn, ', ' + sig if sig else ''))
        if n == 'vsprintf':
            o.append('    return gcnr_call_vsprintf(0x%08Xu, a0, a1, a2);\n}\n' % game[n])
            continue
        if n == 'main':
            o.append('    gcnr_run_ctors(); /* static constructors first, as __start does */')
        if all(p == 'u32' for p in ps) and ret in ('void', 'u32'):
            o.append('    const uint32_t args[] = {%s};' % (', '.join('a%d' % i for i in range(len(ps))) or '0'))
            call = 'gcnr_call_guest(0x%08Xu, %d, args)' % (game[n], len(ps))
            o.append('    %s%s;\n}\n' % ('return ' if ret != 'void' else '', call))
            continue
        # floating point or 64-bit (mods calling the game): PowerPC EABI registers, as hle_<name>
        # takes them apart above
        o.append('    gcnr_ctx c;\n    gcnr_init_ctx(&c);')
        gpr, fpr = 3, 1
        for i, p in enumerate(ps):
            if p == 'u64':
                gpr += gpr % 2 == 0
                o.append('    c.r[%d] = (uint32_t)(a%d >> 32);\n    c.r[%d] = (uint32_t)a%d;' % (gpr, i, gpr + 1, i))
                gpr += 2
            elif p in ('f32', 'f64'):
                o.append('    c.f[%d].ps0 = c.f[%d].ps1 = (double)a%d;' % (fpr, fpr, i))
                fpr += 1
            else:
                o.append('    c.r[%d] = a%d;' % (gpr, i))
                gpr += 1
        if gpr > 11 or fpr > 9:
            raise SystemExit('gen_hle_glue: %s takes more arguments than fit in registers' % n)
        o.append('    gcnr_call_ctx(&c, 0x%08Xu);' % game[n])
        if ret == 'u64':
            o.append('    return (uint64_t)c.r[3] << 32 | c.r[4];')
        elif ret in ('f32', 'f64'):
            o.append('    return (%s)c.f[1].ps0;' % ('float' if ret == 'f32' else 'double'))
        elif ret == 'u32':
            o.append('    return c.r[3];')
        o.append('}\n')

    o.append('/* the wrappers by name: a Live build finds them by the addresses syms.txt gives those names */')
    o.append('const gcnr_named_func gcnr_hle_functions[] = {')
    o += ['    {"%s", hle_%s},' % (n, n) for n in hle if n not in missing]
    o.append('    {0, 0},\n};')

    with open(out_path, 'w', newline='\n') as f:
        f.write('\n'.join(o) + '\n')
    print('gen_hle_glue: %d wrappers, %d game functions%s' % (len(hle) - len(missing), sum(1 for n in imports if n in game),
                                                              (', missing exports: ' + ' '.join(missing)) if missing else ''))
    return 1 if missing else 0


if __name__ == '__main__':
    sys.exit(main())
