/**
 * @file main.cpp
 * @brief GcnRecomp: recompiles a GameCube DOL to C.
 *
 *   GcnRecomp --dol main.dol --syms syms.txt --out <dir> [--per-file N] [--no-comments]
 *
 * Writes into <dir>:
 *   funcs.h          prototypes of every recompiled function (f_ADDR) and every HLE function (hle_NAME)
 *   funcs_NNN.c      the recompiled functions
 *   functable.c      gcnr_functions[]: address -> function, sorted (indirect calls, threads, callbacks)
 *   game.c           gcnr_game: entry point, r1/r2/r13, the DOL's sha1, the HLE names
 *   recomp_report.txt warnings (unresolved branches, jump tables) and statistics
 */
#include "analysis.h"
#include "generator.h"
#include "program.h"

#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

using namespace gcnr;
namespace fs = std::filesystem;

static bool write_file(const fs::path& path, const std::string& text)
{
    // unchanged files keep their time stamps (so a rebuild only recompiles what changed)
    std::ifstream in(path, std::ios::binary);
    if (in)
    {
        std::string old((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
        if (old == text)
        {
            return true;
        }
    }
    std::ofstream out(path, std::ios::binary);
    out << text;
    return (bool)out;
}

int main(int argc, char** argv)
{
    std::string dolPath, symsPath, outDir;
    int perFile = 250;
    GenOptions options;
    for (int i = 1; i < argc; i++)
    {
        const std::string a = argv[i];
        if (a == "--dol" && i + 1 < argc) dolPath = argv[++i];
        else if (a == "--syms" && i + 1 < argc) symsPath = argv[++i];
        else if (a == "--out" && i + 1 < argc) outDir = argv[++i];
        else if (a == "--per-file" && i + 1 < argc) perFile = std::max(1, std::atoi(argv[++i]));
        else if (a == "--no-comments") options.comments = false;
        else if (a == "--check-sp-all") options.checkSp = true;
        else if (a == "--trace" && i + 1 < argc)
        {
            // --trace 0x80135FB4,0x8003B9EC: log r3-r8 / f1 on entry (debugging)
            std::string list = argv[++i];
            size_t pos = 0;
            while (pos < list.size())
            {
                size_t comma = list.find(',', pos);
                if (comma == std::string::npos) comma = list.size();
                options.traced.insert((uint32_t)std::stoul(list.substr(pos, comma - pos), nullptr, 16));
                pos = comma + 1;
            }
        }
        else
        {
            std::fprintf(stderr, "usage: GcnRecomp --dol main.dol --syms syms.txt --out dir [--per-file N] [--no-comments]\n");
            return 2;
        }
    }
    if (dolPath.empty() || symsPath.empty() || outDir.empty())
    {
        std::fprintf(stderr, "GcnRecomp: --dol, --syms and --out are required\n");
        return 2;
    }

    Program program;
    std::string error;
    if (!program.load_dol(dolPath, error) || !program.load_symbols(symsPath, error))
    {
        std::fprintf(stderr, "GcnRecomp: %s\n", error.c_str());
        return 1;
    }
    std::vector<std::string> warnings;
    const int extras = find_extra_entries(program, warnings);

    fs::create_directories(outDir);
    CGenerator gen(options);
    std::string header = "/* Generated by GcnRecomp. Do not edit. */\n#pragma once\n#include \"gcn_recomp.h\"\n\n";
    std::string table = "/* Generated by GcnRecomp. Do not edit. */\n#include \"funcs.h\"\n\n"
                        "typedef struct gcnr_function { uint32_t addr; gcnr_func fn; } gcnr_function;\n"
                        "const gcnr_function gcnr_functions[] = {\n";
    std::string body, lrStubs;
    int lrFunctions = 0;
    int fileIndex = 0, inFile = 0, recompiled = 0, hle = 0, stubs = 0, switches = 0, mmioSites = 0, loops = 0, spins = 0;
    size_t instructions = 0;
    auto flush = [&](bool force) {
        if (inFile == 0 || (!force && inFile < perFile))
        {
            return;
        }
        char name[32];
        std::snprintf(name, sizeof(name), "funcs_%03d.c", fileIndex++);
        write_file(fs::path(outDir) / name,
                   "/* Generated by GcnRecomp. Do not edit. */\n#include \"funcs.h\"\n\n" + body);
        body.clear();
        inFile = 0;
    };

    for (const auto& [addr, f] : program.functions)
    {
        header += "void " + f.c_name() + "(uint8_t* mem, gcnr_ctx* c);";
        header += f.name.empty() ? "\n" : "  /* " + f.name + " */\n";
        char entry[96];
        std::snprintf(entry, sizeof(entry), "    {0x%08Xu, %s},\n", addr, f.c_name().c_str());
        table += entry;
        if (f.hle)
        {
            hle++;
            continue;
        }
        if (f.stub)
        {
            // syms.txt `stub`: hardware the runtime does not have (returns the value in r3)
            char stub[160];
            std::snprintf(stub, sizeof(stub), "void %s(uint8_t* mem, gcnr_ctx* c)\n{\n    (void)mem;\n    c->r[3] = 0x%Xu;\n}\n\n",
                          f.c_name().c_str(), f.stubValue);
            body += "/* " + (f.name.empty() ? f.c_name() : f.name) + ": stub */\n" + stub;
            stubs++;
            inFile++;
            flush(false);
            continue;
        }
        // an entry point inside an LR-mode function enters that function's body
        if (f.extra)
        {
            const Function* parent = program.function_containing(f.addr);
            if (parent && !parent->hle && needs_lr_mode(program, *parent))
            {
                char stub[160];
                std::snprintf(stub, sizeof(stub), "void %s(uint8_t* mem, gcnr_ctx* c)\n{\n    %s_body(mem, c, 0x%08Xu);\n}\n\n",
                              f.c_name().c_str(), parent->c_name().c_str(), f.addr);
                lrStubs += stub;
                continue;
            }
        }
        const Analysis an = analyze(program, f);
        lrFunctions += an.lrMode;
        if (an.lrMode)
        {
            header += "void " + f.c_name() + "_body(uint8_t* mem, gcnr_ctx* c, uint32_t entry);\n";
        }
        for (const std::string& w : an.warnings)
        {
            warnings.push_back((f.name.empty() ? f.c_name() : f.name) + ": " + w);
        }
        switches += (int)an.switches.size();
        loops += (int)an.backBranches.size();
        spins += (int)an.spinLoops.size();
        for (const auto& [at, ea] : an.knownEa)
        {
            mmioSites += (ea >> 24) == 0xCC;
        }
        instructions += an.insns.size();
        if (!f.name.empty())
        {
            body += "/* " + f.name + " */\n";
        }
        gen.function(program, an, body);
        recompiled++;
        inFile++;
        flush(false);
    }
    body += lrStubs; // entry points into LR-mode bodies (declared in funcs.h)
    flush(true);
    table += "};\nconst uint32_t gcnr_function_count = sizeof(gcnr_functions) / sizeof(gcnr_functions[0]);\n";

    std::string game = "/* Generated by GcnRecomp. Do not edit. */\n#include <stdint.h>\n\n";
    char buf[1024];
    std::snprintf(buf, sizeof(buf),
                  "const uint32_t gcnr_entry = 0x%08Xu;\nconst uint32_t gcnr_r1 = 0x%08Xu;\nconst uint32_t gcnr_r2 = 0x%08Xu;\n"
                  "const uint32_t gcnr_r13 = 0x%08Xu;\nconst uint32_t gcnr_ctors = 0x%08Xu;\nconst char gcnr_dol_sha1[] = \"%s\";\n",
                  program.entry, program.r1, program.r2, program.r13, program.ctors, program.dolSha1.c_str());
    game += buf;

    write_file(fs::path(outDir) / "funcs.h", header);
    write_file(fs::path(outDir) / "functable.c", table);
    write_file(fs::path(outDir) / "game.c", game);

    std::string report;
    std::snprintf(buf, sizeof(buf),
                  "functions: %d recompiled (%d extra entry points), %d HLE, %d stubs\ninstructions: %zu\n"
                  "jump tables: %d\nloops: %d (%d busy-wait: no stores, no calls)\nhardware register accesses found: %d\n"
                  "warnings: %zu\n\n",
                  recompiled, extras, hle, stubs, instructions, switches, loops, spins, mmioSites, warnings.size());
    report += buf;
    for (const std::string& w : warnings)
    {
        report += w + "\n";
    }
    write_file(fs::path(outDir) / "recomp_report.txt", report);
    std::printf("%s", report.substr(0, report.find("\n\n") + 1).c_str());
    std::printf("output: %s (%d files)\n", outDir.c_str(), fileIndex);
    return 0;
}
