"""Writes call_test_stubs.c: every hle_* function in GcnRecomp's funcs.h and every runtime hook
gcn_recomp.h declares, as a stub that aborts (call_test.c calls self-contained game code only).

    python make_call_test_stubs.py <GcnRecomp out dir>/funcs.h <out.c>
"""
import re
import sys

funcs_h, out = sys.argv[1], sys.argv[2]
names = re.findall(r'^void (hle_\w+)\(uint8_t\* mem, gcnr_ctx\* c\);', open(funcs_h).read(), re.M)
o = ['/* generated by make_call_test_stubs.py */', '#include <stdio.h>', '#include <stdlib.h>', '#include "gcn_recomp.h"', '',
     'static void stub(const char* name) { fprintf(stderr, "call_test: %s called\\n", name); exit(3); }']
for n in names:
    o.append('void %s(uint8_t* mem, gcnr_ctx* c) { (void)mem; (void)c; stub("%s"); }' % (n, n))
o += [
    'void gcnr_loop_poll(uint8_t* mem, gcnr_ctx* c) { (void)mem; c->loop = 0; }',
    'uint32_t gcnr_mmio_read(uint32_t a, int n) { (void)n; fprintf(stderr, "mmio read %08X\\n", a); return 0; }',
    'void gcnr_mmio_write(uint32_t a, uint32_t v, int n) { (void)a; (void)v; (void)n; }',
    'void gcnr_psq_st_mmio(gcnr_ctx* c, int fs, uint32_t a, int w, int i) { (void)c; (void)fs; (void)a; (void)w; (void)i; }',
    'void gcnr_checked_access(uint32_t a, int w) { (void)a; (void)w; }',
    'uint32_t gcnr_mfspr(gcnr_ctx* c, uint32_t s) { (void)c; (void)s; return 0; }',
    'void gcnr_mtspr(gcnr_ctx* c, uint32_t s, uint32_t v) { (void)c; (void)s; (void)v; }',
    'uint64_t gcnr_timebase(void) { return 0; }',
    'void gcnr_syscall(uint8_t* mem, gcnr_ctx* c) { (void)mem; (void)c; }',
    'void gcnr_trap(gcnr_ctx* c, uint32_t a) { (void)c; fprintf(stderr, "trap %08X\\n", a); exit(3); }',
    'void gcnr_unhandled(gcnr_ctx* c, uint32_t a, const char* w) { (void)c; fprintf(stderr, "%s at %08X\\n", w, a); exit(3); }',
    'void gcnr_trace_func(uint32_t a, uint8_t* mem, const gcnr_ctx* c) { (void)a; (void)mem; (void)c; }',
    'void gcnr_sp_changed(uint32_t at, uint32_t callee, uint32_t b, uint32_t a) { (void)at; (void)callee; (void)b; (void)a; }',
    'uint32_t gcnr_watch_addr = 0xFFFFFFFFu;',
    'void gcnr_watch_hit(uint32_t a, uint64_t v, int n) { (void)a; (void)v; (void)n; }',
]
open(out, 'w', newline='\n').write('\n'.join(o) + '\n')
print('%d HLE stubs' % len(names))
