"""Compiles the GameCube GPU shaders (gcn_vk.vert, gcn_vk_xf.vert, gcn_vk.frag: GLSL) to SPIR-V and writes them
into Source/Gcn/gcn_vk_spv.h as C arrays, so the addon needs no shader compiler.

    python gen_spv.py [--glslc <path>]   (default: %VULKAN_SDK%/Bin/glslc, then glslc on PATH)
"""
import argparse, os, shutil, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, '..', '..', '..', 'Source', 'Gcn', 'gcn_vk_spv.h'))


def find_glslc(arg):
    if arg:
        return arg
    sdk = os.environ.get('VULKAN_SDK')
    for c in ([os.path.join(sdk, 'Bin', 'glslc.exe'), os.path.join(sdk, 'bin', 'glslc')] if sdk else []):
        if os.path.isfile(c):
            return c
    c = shutil.which('glslc')
    if c:
        return c
    sys.exit('gen_spv: glslc not found (install the Vulkan SDK or pass --glslc)')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--glslc')
    a = ap.parse_args()
    glslc = find_glslc(a.glslc)
    parts = ['/* Generated by Runtime/tools/gpu/gen_spv.py from gcn_vk.vert / gcn_vk.frag: do not edit. */\n',
             '#pragma once\n#include <stdint.h>\n']
    with tempfile.TemporaryDirectory() as tmp:
        for src, name in (('gcn_vk.vert', 'gcn_vk_vert_spv'), ('gcn_vk_xf.vert', 'gcn_vk_xf_vert_spv'),
                          ('gcn_vk.frag', 'gcn_vk_frag_spv')):
            out = os.path.join(tmp, name + '.spv')
            subprocess.run([glslc, '--target-env=vulkan1.2', '-O', os.path.join(HERE, src), '-o', out], check=True)
            data = open(out, 'rb').read()
            words = [int.from_bytes(data[i:i + 4], 'little') for i in range(0, len(data), 4)]
            lines = []
            for i in range(0, len(words), 8):
                lines.append('    ' + ', '.join('0x%08Xu' % w for w in words[i:i + 8]) + ',')
            parts.append('static const uint32_t %s[%d] = {\n%s\n};\n' % (name, len(words), '\n'.join(lines)))
    open(OUT, 'w', newline='\n').write('\n'.join(parts))
    print('gen_spv: wrote', OUT)


if __name__ == '__main__':
    main()
