"""Compiles the GameCube GPU shaders (gcn_vk.vert, gcn_vk_xf.vert, gcn_vk.frag and the display
post-processing passes gcn_post_*.comp: GLSL) to SPIR-V and writes them into
Source/Gcn/gcn_vk_spv.h as C arrays, so the addon needs no shader compiler. Also writes SMAA's
lookup textures (third_party/smaa AreaTex.h / SearchTex.h) into Source/Gcn/gcn_vk_post_tex.h.

    python gen_spv.py [--glslc <path>]   (default: %VULKAN_SDK%/Bin/glslc, then glslc on PATH)

Third-party code (MIT): third_party/fsr1 (AMD FidelityFX Super Resolution 1: ffx_a.h,
ffx_fsr1.h) and third_party/smaa (SMAA, Jimenez et al.: SMAA.hlsl, AreaTex.h, SearchTex.h). SMAA's
edge detection ends with `discard` when a pixel has no edge, which compute shaders don't have: the
copy compiled here returns no edge (0, 0) instead, what the discarded pixel would have left.
"""
import argparse, os, re, shutil, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_GCN = os.path.normpath(os.path.join(HERE, '..', '..', '..', 'Source', 'Gcn'))
OUT = os.path.join(SRC_GCN, 'gcn_vk_spv.h')
OUT_TEX = os.path.join(SRC_GCN, 'gcn_vk_post_tex.h')
FSR = os.path.join(HERE, 'third_party', 'fsr1')
SMAA = os.path.join(HERE, 'third_party', 'smaa')

SHADERS = (('gcn_vk.vert', 'gcn_vk_vert_spv'), ('gcn_vk_xf.vert', 'gcn_vk_xf_vert_spv'),
           ('gcn_vk.frag', 'gcn_vk_frag_spv'),
           ('gcn_post_smaa_edge.comp', 'gcn_post_smaa_edge_spv'),
           ('gcn_post_smaa_weight.comp', 'gcn_post_smaa_weight_spv'),
           ('gcn_post_smaa_blend.comp', 'gcn_post_smaa_blend_spv'),
           ('gcn_post_easu.comp', 'gcn_post_easu_spv'),
           ('gcn_post_rcas.comp', 'gcn_post_rcas_spv'))


def find_glslc(arg):
    if arg:
        return arg
    sdk = os.environ.get('VULKAN_SDK')
    for c in ([os.path.join(sdk, 'Bin', 'glslc.exe'), os.path.join(sdk, 'bin', 'glslc')] if sdk else []):
        if os.path.isfile(c):
            return c
    c = shutil.which('glslc')
    if c:
        return c
    sys.exit('gen_spv: glslc not found (install the Vulkan SDK or pass --glslc)')


def words_array(name, data):
    words = [int.from_bytes(data[i:i + 4], 'little') for i in range(0, len(data), 4)]
    lines = ['    ' + ', '.join('0x%08Xu' % w for w in words[i:i + 8]) + ',' for i in range(0, len(words), 8)]
    return 'static const uint32_t %s[%d] = {\n%s\n};\n' % (name, len(words), '\n'.join(lines))


def table_bytes(path, name):
    """the byte array `name` of a third-party texture header"""
    text = open(path, encoding='latin-1').read()
    body = text[text.index(name):]
    body = body[body.index('{') + 1:body.index('}')]
    return bytes(int(v, 16) for v in re.findall(r'0x([0-9a-fA-F]{2})', body))


def bytes_array(name, data):
    lines = ['    ' + ','.join(str(b) for b in data[i:i + 32]) + ',' for i in range(0, len(data), 32)]
    return 'static const uint8_t %s[%d] = {\n%s\n};\n' % (name, len(data), '\n'.join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--glslc')
    a = ap.parse_args()
    glslc = find_glslc(a.glslc)
    parts = ['/* Generated by Runtime/tools/gpu/gen_spv.py from gcn_vk.vert / gcn_vk.frag / gcn_post_*.comp: do not edit. */\n',
             '#pragma once\n#include <stdint.h>\n']
    with tempfile.TemporaryDirectory() as tmp:
        smaa = open(os.path.join(SMAA, 'SMAA.hlsl'), encoding='latin-1').read()
        if smaa.count('discard;') != 3:
            sys.exit('gen_spv: SMAA.hlsl changed (expected 3 discards)')
        open(os.path.join(tmp, 'SMAA.glsl'), 'w', encoding='latin-1').write(smaa.replace('discard;', 'return float2(0.0, 0.0);'))
        for src, name in SHADERS:
            out = os.path.join(tmp, name + '.spv')
            subprocess.run([glslc, '--target-env=vulkan1.2', '-O', '-I', tmp, '-I', FSR, '-I', HERE,
                            os.path.join(HERE, src), '-o', out], check=True)
            parts.append(words_array(name, open(out, 'rb').read()))
    open(OUT, 'w', newline='\n').write('\n'.join(parts))
    print('gen_spv: wrote', OUT)

    area = table_bytes(os.path.join(SMAA, 'AreaTex.h'), 'areaTexBytes')
    search = table_bytes(os.path.join(SMAA, 'SearchTex.h'), 'searchTexBytes')
    if len(area) != 160 * 560 * 2 or len(search) != 64 * 16:
        sys.exit('gen_spv: unexpected SMAA texture sizes %d / %d' % (len(area), len(search)))
    tex = ['/* Generated by Runtime/tools/gpu/gen_spv.py from third_party/smaa AreaTex.h / SearchTex.h (MIT, Jimenez',
           ' * et al., see third_party/smaa/LICENSE.txt): SMAA\'s lookup textures. Do not edit. */',
           '#pragma once', '#include <stdint.h>', '',
           '#define GCN_SMAA_AREA_W 160', '#define GCN_SMAA_AREA_H 560 /* R8G8 */',
           '#define GCN_SMAA_SEARCH_W 64', '#define GCN_SMAA_SEARCH_H 16 /* R8 */', '',
           bytes_array('gcn_smaa_area', area), bytes_array('gcn_smaa_search', search)]
    open(OUT_TEX, 'w', newline='\n').write('\n'.join(tex))
    print('gen_spv: wrote', OUT_TEX)


if __name__ == '__main__':
    main()
