#!/usr/bin/env python3
"""Data a decomp leaves in the retail executable, cut from the user's own disc at build time.

decomp-toolkit projects list such symbols under `extract:` in config/<version>/config.yml
(binary blobs the C #includes as generated headers). This writes the same headers from
the DOL on the user's disc, so the port builds without running the decomp's own build:

    gcn_extract.py <decomp> <version> <disc image> <out_dir>

Headers are written as `<out_dir>/<header>` (byte arrays named after the symbol).
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gcn_disc  # noqa: E402


def extract_entries(config_yml):
    """The `extract:` list of a dtk config.yml (symbol / binary / header keys)."""
    entries, cur, inside = [], None, False
    for line in open(config_yml, encoding='utf-8'):
        if re.match(r'^extract:\s*$', line):
            inside = True
            continue
        if inside:
            if re.match(r'^[A-Za-z_]', line):
                break
            m = re.match(r'^\s*-\s*(\w+):\s*(.*?)\s*$', line)
            if m:
                cur = {m.group(1): m.group(2)}
                entries.append(cur)
                continue
            m = re.match(r'^\s+(\w+):\s*(.*?)\s*$', line)
            if m and cur is not None:
                cur[m.group(1)] = m.group(2)
    return entries


def symbols(symbols_txt):
    out = {}
    for line in open(symbols_txt, encoding='utf-8'):
        m = re.match(r'^(\S+) = \.?\w+:0x([0-9A-Fa-f]+);.*?size:0x([0-9A-Fa-f]+)', line)
        if m:
            out[m.group(1)] = (int(m.group(2), 16), int(m.group(3), 16))
    return out


def main():
    decomp, version, disc, out_dir = sys.argv[1:5]
    cfgdir = os.path.join(decomp, 'config', version)
    entries = extract_entries(os.path.join(cfgdir, 'config.yml'))
    if not entries:
        return 0
    syms = symbols(os.path.join(cfgdir, 'symbols.txt'))
    dol = None
    for e in entries:
        name, header = e.get('symbol'), e.get('header')
        if not name or not header:
            continue
        dst = os.path.join(out_dir, header)
        if os.path.exists(dst) and os.path.getmtime(dst) >= os.path.getmtime(disc):
            continue
        if dol is None:
            dol = gcn_disc.Dol(gcn_disc.Disc(disc).dol())
        addr, size = syms[name]
        data = dol.read(addr, size)
        lines = ['/* %s: 0x%X bytes at 0x%08X of the retail DOL (generated by gcn_extract.py) */' % (name, size, addr),
                 'unsigned char %s[0x%X] __attribute__((aligned(32))) = {' % (name, size)]
        for i in range(0, size, 32):
            lines.append('    ' + ', '.join('0x%02X' % b for b in data[i:i + 32]) + ',')
        lines.append('};')
        os.makedirs(os.path.dirname(dst) or '.', exist_ok=True)
        open(dst, 'w', newline='\n').write('\n'.join(lines) + '\n')
        print('gcn_extract: %s (%d bytes)' % (header, size))
    return 0


if __name__ == '__main__':
    sys.exit(main())
