/*
 * Dolphin SDK OS replacement, the parts that are not threads (thread.c): boot, arena,
 * time, interrupts, reports, system settings and caches.
 */
#include <dolphin.h>
#include <dolphin/os.h>
#include <stdarg.h>
#include <string.h>

#include "gcn_guest.h"
#include "gcn_sdk.h"

int vsprintf(char *s, const char *fmt, va_list ap);
int main(int argc, char **argv);
void gcn_mods_init_all(void); /* generated by gcn_build.py from Native/mods */

#define WEAK __attribute__((weak))

/* ---- boot ---------------------------------------------------------------------------- */
static void *sArenaLo, *sArenaHi;
static int sBooted;

void gcn_boot(u32 arena_lo)
{
    char *argv[2];

    sArenaLo = (void *)((arena_lo + 31) & ~31u);
    sArenaHi = (void *)(0x81800000u - GCN_FST_RESERVE);
    gcn_threads_init();
    gcn_dvd_init();
    sBooted = 1;
    gcn_logf("gcn: boot, arena %08X-%08X", (u32)sArenaLo, (u32)sArenaHi);
    gcn_mods_init_all();
    argv[0] = "main.dol";
    argv[1] = 0;
    main(1, argv);
    gcn_host_fatal("main() returned");
}

WEAK void *OSGetArenaLo(void) { return sArenaLo; }
WEAK void *OSGetArenaHi(void) { return sArenaHi; }
WEAK void OSSetArenaLo(void *lo) { sArenaLo = lo; }
WEAK void OSSetArenaHi(void *hi) { sArenaHi = hi; }

WEAK void *OSAllocFromArenaLo(u32 size, u32 align)
{
    u32 p = ((u32)sArenaLo + align - 1) & ~(align - 1);
    sArenaLo = (void *)(((p + size) + align - 1) & ~(align - 1));
    return (void *)p;
}

WEAK void *OSAllocFromArenaHi(u32 size, u32 align)
{
    u32 p = ((u32)sArenaHi - size) & ~(align - 1);
    sArenaHi = (void *)p;
    return (void *)p;
}

WEAK void OSInit(void) {}

WEAK u32 OSGetConsoleType(void) { return OS_CONSOLE_RETAIL1; }
WEAK u32 OSGetPhysicalMemSize(void) { return 0x01800000; }
WEAK u32 OSGetConsoleSimulatedMemSize(void) { return 0x01800000; }

/* ---- time ------------------------------------------------------------------------------ */
WEAK OSTime OSGetTime(void) { return (OSTime)gcn_host_ticks(); }
WEAK OSTick OSGetTick(void) { return (OSTick)gcn_host_ticks(); }

WEAK OSTime __OSGetSystemTime(void) { return (OSTime)gcn_host_ticks(); }

/* ---- interrupts: there are none to mask; events are delivered at scheduling points --- */
static BOOL sInterruptsEnabled = TRUE;

WEAK BOOL OSDisableInterrupts(void)
{
    BOOL old = sInterruptsEnabled;
    sInterruptsEnabled = FALSE;
    return old;
}

WEAK BOOL OSEnableInterrupts(void)
{
    BOOL old = sInterruptsEnabled;
    sInterruptsEnabled = TRUE;
    return old;
}

WEAK BOOL OSRestoreInterrupts(BOOL level)
{
    BOOL old = sInterruptsEnabled;
    sInterruptsEnabled = level;
    return old;
}

/* ---- reports --------------------------------------------------------------------------- */
void gcn_logf(const char *fmt, ...)
{
    char buf[512];
    va_list ap;

    va_start(ap, fmt);
    vsprintf(buf, fmt, ap);
    va_end(ap);
    gcn_host_log(buf);
}

/* Game diagnostics a port patch forwards (retail builds drop them). A format that keeps
 * coming is shown a few times only. */
void gcn_game_vlog(const char *fmt, va_list ap)
{
    static const char *seen[64];
    static u8 count[64];
    char buf[512];
    int i;

    for (i = 0; i < 64 && seen[i] && seen[i] != fmt; i++)
    {
    }
    if (i < 64)
    {
        seen[i] = fmt;
        if (count[i] >= 4) return;
        count[i]++;
    }
    vsprintf(buf, fmt, ap);
    {
        size_t n = strlen(buf);
        while (n && (buf[n - 1] == '\n' || buf[n - 1] == '\r')) buf[--n] = 0;
    }
    gcn_logf(i < 64 && count[i] == 4 ? "game: %s (repeats; not shown again)" : "game: %s", buf);
}

WEAK void OSReport(const char *fmt, ...)
{
    char buf[512];
    va_list ap;

    va_start(ap, fmt);
    vsprintf(buf, fmt, ap);
    va_end(ap);
    gcn_host_log(buf);
}

WEAK void OSVReport(const char *fmt, va_list ap)
{
    char buf[512];

    vsprintf(buf, fmt, ap);
    gcn_host_log(buf);
}

WEAK void OSPanic(const char *file, int line, const char *fmt, ...)
{
    char buf[512];
    char msg[640];
    va_list ap;

    va_start(ap, fmt);
    vsprintf(buf, fmt, ap);
    va_end(ap);
    sprintf(msg, "OSPanic %s:%d: %s", file, line, buf);
    gcn_host_fatal(msg);
}

WEAK void OSFatal(GXColor fg, GXColor bg, const char *msg)
{
    gcn_host_fatal(msg);
}

/* ---- system settings (SRAM) ------------------------------------------------------------ */
static u32 sSoundMode = OS_SOUND_MODE_STEREO;
static u32 sProgressive;

WEAK u32 OSGetSoundMode(void) { return sSoundMode; }
WEAK void OSSetSoundMode(u32 mode) { sSoundMode = mode; }
WEAK u32 OSGetProgressiveMode(void) { return sProgressive; }
WEAK void OSSetProgressiveMode(u32 on) { sProgressive = on; }
WEAK u8 OSGetLanguage(void) { return OS_LANGUAGE_ENGLISH; }
WEAK void OSSetLanguage(u8 language) {}
WEAK u16 OSGetWirelessID(s32 chan) { return 0; }
WEAK void OSSetWirelessID(s32 chan, u16 id) {}
WEAK u32 OSGetResetCode(void) { return 0; }
WEAK BOOL OSGetResetButtonState(void) { return FALSE; }
WEAK BOOL OSGetResetSwitchState(void) { return FALSE; }
WEAK void OSSetSaveRegion(void *start, void *end) {}

WEAK void OSResetSystem(int reset, u32 resetCode, BOOL forceMenu)
{
    gcn_host_fatal("OSResetSystem");
}

WEAK OSErrorHandler OSSetErrorHandler(OSError error, OSErrorHandler handler) { return 0; }

/* ---- stopwatch ------------------------------------------------------------------------- */
WEAK void OSInitStopwatch(OSStopwatch *sw, char *name)
{
    sw->name = name;
    sw->total = 0;
    sw->hits = 0;
    sw->min = 0x00000000FFFFFFFFLL;
    sw->max = 0;
    sw->running = 0;
}

WEAK void OSStartStopwatch(OSStopwatch *sw)
{
    sw->running = 1;
    sw->last = OSGetTime();
}

WEAK void OSStopStopwatch(OSStopwatch *sw)
{
    OSTime t;

    if (sw->running)
    {
        t = OSGetTime() - sw->last;
        sw->total += t;
        sw->running = 0;
        sw->hits++;
        if (sw->max < t) sw->max = t;
        if (t < sw->min) sw->min = t;
    }
}

WEAK OSTime OSCheckStopwatch(OSStopwatch *sw)
{
    OSTime t = sw->total;
    if (sw->running) t += OSGetTime() - sw->last;
    return t;
}

WEAK void OSResetStopwatch(OSStopwatch *sw)
{
    OSInitStopwatch(sw, sw->name);
}

/* ---- caches: the host has coherent memory -------------------------------------------- */
/* the GPU reads memory behind the CPU caches: on hosts where that is so (Wii) the host makes
 * these real; on others they cost a call */
WEAK void DCFlushRange(void *addr, u32 nBytes) { gcn_host_dcache(0, addr, nBytes); }
WEAK void DCFlushRangeNoSync(void *addr, u32 nBytes) { gcn_host_dcache(0, addr, nBytes); }
WEAK void DCStoreRange(void *addr, u32 nBytes) { gcn_host_dcache(1, addr, nBytes); }
WEAK void DCStoreRangeNoSync(void *addr, u32 nBytes) { gcn_host_dcache(1, addr, nBytes); }
WEAK void DCInvalidateRange(void *addr, u32 nBytes) { gcn_host_dcache(2, addr, nBytes); }
WEAK void DCZeroRange(void *addr, u32 nBytes) { memset(addr, 0, nBytes); }
WEAK void ICInvalidateRange(void *addr, u32 nBytes) {}
WEAK void ICFlashInvalidate(void) {}

/* Locked cache: 16 KB at 0xE0000000, a separate window of guest memory (host gcnw.h). */
WEAK void LCEnable(void) {}
WEAK void LCDisable(void) {}

WEAK u32 LCLoadData(void *destAddr, void *srcAddr, u32 nBytes)
{
    memcpy(destAddr, srcAddr, nBytes);
    return (nBytes + 0xFFF) / 0x1000;
}

WEAK u32 LCStoreData(void *destAddr, void *srcAddr, u32 nBytes)
{
    memcpy(destAddr, srcAddr, nBytes);
    gcn_host_dcache(0, destAddr, nBytes); /* a DMA to memory on the console */
    return (nBytes + 0xFFF) / 0x1000;
}

WEAK void LCLoadBlocks(void *destTag, void *srcAddr, u32 numBlocks)
{
    memcpy(destTag, srcAddr, (numBlocks ? numBlocks : 128) * 32);
}

WEAK void LCStoreBlocks(void *destAddr, void *srcTag, u32 numBlocks)
{
    memcpy(destAddr, srcTag, (numBlocks ? numBlocks : 128) * 32);
    gcn_host_dcache(0, destAddr, (numBlocks ? numBlocks : 128) * 32);
}

WEAK void LCQueueWait(u32 len) {}
WEAK void LCFlushQueue(void) {}

WEAK void PPCSync(void) {}
WEAK u32 PPCMfwpar(void) { return 0; }
WEAK void PPCMtwpar(u32 v) {}
WEAK void PPCHalt(void) { gcn_host_fatal("PPCHalt"); }
